export interface ResumeTemplate {
  id: string;
  name: string;
  category: "simple" | "modern" | "creative";
  desc: string;
  accent: string;
  bg: string;
  sidebarBg?: string;
  textColor: string;
  mutedColor: string;
  layout: "classic-center" | "sidebar-dark" | "harvard" | "modern-teal" | "corporate-clean" | "corporate-dense" | "single-minimal" | "two-col-accent";
}

export const templates: ResumeTemplate[] = [
  // ─── SIMPLE ──────────────────────────────────────────
  {
    id: "classic-center",
    name: "Classic",
    category: "simple",
    desc: "Center-aligned name, serif font, clean section dividers",
    accent: "#000000",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "classic-center",
  },
  {
    id: "harvard",
    name: "Harvard",
    category: "simple",
    desc: "Classic academic style with centered headers and thin lines",
    accent: "#000000",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "harvard",
  },
  {
    id: "executive",
    name: "Executive",
    category: "simple",
    desc: "Professional serif layout for senior executives",
    accent: "#1a1a1a",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "single-minimal",
  },
  {
    id: "finance",
    name: "Finance",
    category: "simple",
    desc: "Elegant layout for banking & finance professionals",
    accent: "#1e293b",
    bg: "#ffffff",
    textColor: "#0f172a",
    mutedColor: "#475569",
    layout: "single-minimal",
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    category: "simple",
    desc: "Minimalist design with generous whitespace",
    accent: "#374151",
    bg: "#ffffff",
    textColor: "#111827",
    mutedColor: "#6b7280",
    layout: "classic-center",
  },
  {
    id: "refined",
    name: "Refined",
    category: "simple",
    desc: "Subtle elegance with fine line details",
    accent: "#44403c",
    bg: "#fafaf9",
    textColor: "#1c1917",
    mutedColor: "#78716c",
    layout: "harvard",
  },

  // ─── MODERN ──────────────────────────────────────────
  {
    id: "corporate-clean",
    name: "Corporate Clean",
    category: "modern",
    desc: "Teal accent headers with organized clean layout",
    accent: "#1e6b7b",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "corporate-clean",
  },
  {
    id: "corporate-dense",
    name: "Corporate Pro",
    category: "modern",
    desc: "Dense single-column for detailed experience",
    accent: "#1e6b7b",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "corporate-dense",
  },
  {
    id: "modern-teal",
    name: "Modern Teal",
    category: "modern",
    desc: "Teal accents with centered colored section headers",
    accent: "#2a7f8e",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "modern-teal",
  },
  {
    id: "tech-blue",
    name: "Tech Blue",
    category: "modern",
    desc: "Blue accent layout for tech professionals",
    accent: "#2563eb",
    bg: "#ffffff",
    textColor: "#1e293b",
    mutedColor: "#64748b",
    layout: "corporate-clean",
  },
  {
    id: "startup-green",
    name: "Startup Green",
    category: "modern",
    desc: "Fresh green accents for startup roles",
    accent: "#15803d",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "corporate-clean",
  },
  {
    id: "slate-modern",
    name: "Slate Modern",
    category: "modern",
    desc: "Warm slate tones with modern structure",
    accent: "#475569",
    bg: "#ffffff",
    textColor: "#0f172a",
    mutedColor: "#64748b",
    layout: "corporate-dense",
  },
  {
    id: "indigo-pro",
    name: "Indigo Pro",
    category: "modern",
    desc: "Indigo accents for creative professionals",
    accent: "#4f46e5",
    bg: "#ffffff",
    textColor: "#1e1b4b",
    mutedColor: "#6b7280",
    layout: "two-col-accent",
  },
  {
    id: "cobalt-edge",
    name: "Cobalt Edge",
    category: "modern",
    desc: "Bold cobalt blue with modern grid layout",
    accent: "#1d4ed8",
    bg: "#ffffff",
    textColor: "#1e293b",
    mutedColor: "#64748b",
    layout: "two-col-accent",
  },

  // ─── CREATIVE ────────────────────────────────────────
  {
    id: "sidebar-navy",
    name: "Atlantic Navy",
    category: "creative",
    desc: "Dark navy sidebar with photo and contact info",
    accent: "#f0f0f0",
    bg: "#ffffff",
    sidebarBg: "#1e293b",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "sidebar-emerald",
    name: "Emerald Mist",
    category: "creative",
    desc: "Deep emerald sidebar with elegant layout",
    accent: "#f0f0f0",
    bg: "#ffffff",
    sidebarBg: "#064e3b",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "sidebar-purple",
    name: "Lavender",
    category: "creative",
    desc: "Rich purple sidebar for a unique look",
    accent: "#f0f0f0",
    bg: "#ffffff",
    sidebarBg: "#4c1d95",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "sidebar-coral",
    name: "Coral Navy",
    category: "creative",
    desc: "Dark sidebar with warm coral accents",
    accent: "#f97316",
    bg: "#ffffff",
    sidebarBg: "#1e293b",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "sidebar-charcoal",
    name: "Charcoal",
    category: "creative",
    desc: "Deep charcoal sidebar, modern feel",
    accent: "#f0f0f0",
    bg: "#ffffff",
    sidebarBg: "#18181b",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "modern-rose",
    name: "Rose Gold",
    category: "creative",
    desc: "Elegant rose accents with clean structure",
    accent: "#be185d",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#6b7280",
    layout: "corporate-clean",
  },
  {
    id: "midnight",
    name: "Midnight",
    category: "creative",
    desc: "Dark theme with teal accents for tech roles",
    accent: "#2dd4bf",
    bg: "#ffffff",
    sidebarBg: "#0f172a",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "sidebar-dark",
  },
  {
    id: "sunset",
    name: "Sunset",
    category: "creative",
    desc: "Warm orange-red accents with bold headers",
    accent: "#e11d48",
    bg: "#ffffff",
    textColor: "#1a1a1a",
    mutedColor: "#555555",
    layout: "modern-teal",
  },
];

export const templateCategories = [
  { id: "all", label: "All Templates" },
  { id: "simple", label: "Simple" },
  { id: "modern", label: "Modern" },
  { id: "creative", label: "Creative" },
] as const;

export function getTemplateById(id: string): ResumeTemplate | undefined {
  return templates.find((t) => t.id === id);
}
